---
- name: Installation apache2 sur deby-cli
  hosts: all
  become: true

  tasks:
    - name: Désactivation du service firewalld
      ansible.builtin.systemd:
        name: firewalld
        enabled: false
        state: stopped
      when: ansible_facts['os_family'] == 'RedHat'
      tags:
        - disable_fwd

    - name: Installation d'Apache
      ansible.builtin.package:
        name: "{{ apache_package_name }}"
        state: present

    - name: Configuration du service Apache
      ansible.builtin.systemd:
        name: "{{ apache_service_name }}"
        enabled: true
        state: started

    - name: Modification du port d'écoute
      ansible.builtin.lineinfile:
        dest: "{{ apache_config_port_file }}"
        regex: ^Listen.+$
        line: Listen {{ apache_port }}
        backup: true
      tags:
        - config_port
      notify:
        - restart_apache

    - name: On force l'exécution des handlers à ce point
      ansible.builtin.meta: flush_handlers
      tags: always

    - name: Tâche finale
      ansible.builtin.debug:
        msg: Fin du traitement
      tags: always

  handlers:
    - name: Redémarrage du service Apache
      ansible.builtin.systemd:
        name: "{{ apache_service_name }}"
        state: restarted
      listen:
        - restart_apache
