---
- name: Installation apache2 sur deby-cli
  hosts: all
  become: true

  tasks:
    - name: Installation d'Apache
      ansible.builtin.package:
        name: "{{ apache_package_name }}"
        state: present

    - name: Configuration du service Apache
      ansible.builtin.systemd:
        name: "{{ apache_service_name }}"
        enabled: true
        state: started

    - name: Modification du port d'écoute
      ansible.builtin.lineinfile:
        dest: "{{ apache_config_port_file }}"
        regex: ^Listen.+$
        line: Listen {{ apache_port }}
        backup: true
      tags:
        - config_port

    - name: Redémarrage du service Apache
      ansible.builtin.systemd:
        name: "{{ apache_service_name }}"
        state: restarted
      tags:
        - config_port
