---
- name: Clauses when
  hosts: all

  tasks:
    - name: Block when
      block:
        - name: Clause when I
          ansible.builtin.debug:
            msg: "Distribution OK"

        - name: Clause when II
          ansible.builtin.debug:
            msg: "Version OK"
      when:
        - ansible_facts['os_family'] | lower == 'debian' or apache_port == 80
        - ansible_facts['distribution_major_version'] | int > 11
      tags:
        - never

    - name: Module non-idempotent
      ansible.builtin.raw: date
      changed_when: false
      tags:
        - never

    - name: Gestion de l'état d'erreur
      ansible.builtin.raw: grep "{{ item | default('root') }}" /etc/passwd
      changed_when: false
      register: result
      failed_when: result.rc == 2
      tags:
        - never

    - name: Affichage du code retour
      ansible.builtin.debug:
        msg: "rc: {{ result.rc }}"
      tags:
        - never

    - name: Clause block...rescue...always
      block:
        - name: On teste
          ansible.builtin.raw: grep "{{ item | default('root') }}" /etc/passwd
      rescue:
        - name: Seconde chance
          ansible.builtin.debug:
            msg: "On peut rejouer..."
          failed_when: true
      always:
        - name: À faire quoi qu'il advienne
          ansible.builtin.debug:
            msg: "J'ai pas fini..."

    - name: Tâche finale... si on arrive jusque là
      ansible.builtin.debug:
        msg: "Fini !"
