---
- name: Exemples de loop
  hosts: deby-cli

  tasks:
    - name: Chargement du tableau logins
      ansible.builtin.include_vars:
        file: logins.yml

    - name: Affichage de chaque login
      ansible.builtin.debug:
        msg: "Login n°{{ idx + 1 }}: {{ user.login }} dans {{ user.home }}"
      loop: "{{ logins }}"
      loop_control:
        loop_var: user
        index_var: idx
