---
- name: Clauses when
  hosts: all

  tasks:
    - name: Block when
      block:
        - name: Clause when I
          ansible.builtin.debug:
            msg: "Distribution OK"

        - name: Clause when II
          ansible.builtin.debug:
            msg: "Version OK"
      when:
        - ansible_facts['os_family'] | lower == 'debian' or apache_port == 80
        - ansible_facts['distribution_major_version'] | int > 11
