---
- name: Notion de délégation
  hosts: all

  tasks:
    - name: Fichier /tmp/hosts.txt
      ansible.builtin.lineinfile:
        line: "{{ ansible_facts['enp0s8'].ipv4.address }} {{ ansible_facts['hostname'] }}"
        dest: /tmp/hosts.txt
        create: true
        mode: "0644"
      delegate_to: localhost
